//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AracKiralama.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AracKiralamaRezervasyonEntities : DbContext
    {
        public AracKiralamaRezervasyonEntities()
            : base("name=AracKiralamaRezervasyonEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<adre> adres { get; set; }
        public virtual DbSet<araclar> araclars { get; set; }
        public virtual DbSet<kiralikAraclar> kiralikAraclars { get; set; }
        public virtual DbSet<kullanicilar> kullanicilars { get; set; }
        public virtual DbSet<role> roles { get; set; }
        public virtual DbSet<sirketler> sirketlers { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
    }
}
