//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AracKiralama.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class kiralikAraclar
    {
        public int kiralikAracID { get; set; }
        public Nullable<int> aracID { get; set; }
        public Nullable<int> kullaniciID { get; set; }
        public Nullable<System.DateTime> kiralanmaZamani { get; set; }
        public Nullable<int> verilisKm { get; set; }
        public Nullable<int> sonKilometre { get; set; }
        public Nullable<decimal> ucret { get; set; }
        public Nullable<int> KacGun { get; set; }
    
        public virtual araclar araclar { get; set; }
        public virtual kullanicilar kullanicilar { get; set; }
    }
}
