//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AracKiralama.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class sirketler
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public sirketler()
        {
            this.araclars = new List<araclar>();
        }
    
        public int sirketID { get; set; }
        public string sirketAdi { get; set; }
        public string sehir { get; set; }
        public Nullable<int> adresID { get; set; }
        public Nullable<int> aracSayisi { get; set; }
        public string sirketPuani { get; set; }
    
        public virtual adre adre { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual List<araclar> araclars { get; set; }
    }
}
